TOP = ../../

include $(TOP)/configure/CONFIG

LIBRARY_IOC += mrfApi
mrfApi_SRCS += EVG230Board.cpp EVR230Board.cpp
INC += registers.h
INC += types.h
INC += EVG230Board.h

include $(TOP)/configure/RULES

