TOP = ../../

include $(TOP)/configure/CONFIG

LIBRARY_IOC += mrfApi
mrfApi_SRCS += EVG230Board.cpp evr230.cpp
INC += registers.h
INC += types.h
INC += EVG230Board.h
INC += evr230.h

include $(TOP)/configure/RULES

